networks:
  default:
    name: ${PROJECT_NAME}-network
    external: true

volumes:
  grafana-data:
    driver: local

services:
  grafana:
    image: grafana/grafana:latest
    container_name: ${PROJECT_NAME}-grafana
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./grafana/kafka_dashboard.json:/etc/grafana/provisioning/dashboards/kafka/kafka_dashboard.json
    ports:
      - "3000:3000" # Grafana web UI
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}     
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD} 
    restart: always