apiVersion: batch/v1
kind: Job
metadata:
  name: data-producer
spec:
  template:
    metadata:
      labels:
        app: data-producer
    spec:
      containers:
        - name: data-producer
          image: a92340a/message_data_producer:0.4
          env:
            - name: FILE_PATH
              value: "gs://messages-streaming-project-data/messages.csv"
            - name: BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
      restartPolicy: Never
  backoffLimit: 4
