apiVersion: v1
kind: Service
metadata:
  name: spark-master-service
spec:
  selector:
    app: spark-top
  ports:
    - name: internal
      protocol: TCP
      port: 7077
      targetPort: 7077
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker-service
spec:
  ports:
    - name: worker
      port: 8081
      targetPort: 8081
  selector:
    app: spark-bottom
