apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: default
data:
  # POSTGRES VARIABLES
  POSTGRES_DB: "messaging"
  POSTGRES_USER: "root"
  POSTGRES_PASSWORD: "finnou"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
data:
  # Auto-register PostgresSQL Server
  servers.json: |
    {
        "Servers": {
            "1": {
                "Name": "PostgreSQL",
                "Group": "Servers",
                "Host": "postgres",
                "Port": 5432,
                "Username": "root",
                "Password": "finnou",
                "SSLMode": "disable",
                "MaintenanceDB": "postgres"
            }
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-secret
  namespace: default
data:
  PGADMIN_DEFAULT_EMAIL: "root@gmail.com"
  PGADMIN_DEFAULT_PASSWORD: "1234"
