apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: default
data:
  # POSTGRES VARIABLES
  POSTGRES_DB: "messaging"
  POSTGRES_USER: "root"
  POSTGRES_PASSWORD: "finnou"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
