apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
      annotations:
        gke-gcsfuse/volumes: "true"
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - name: gcs-volume
              mountPath: /mnt/gcs
            - name: init-sql-volume
              mountPath: /docker-entrypoint-initdb.d
      serviceAccountName: default
      volumes:
        - name: gcs-volume
          csi:
            driver: gcsfuse.csi.storage.gke.io
            readOnly: true
            volumeAttributes:
              bucketName: messages-streaming-project-data
              mountOptions: "implicit-dirs"
        - name: init-sql-volume
          configMap:
            name: postgres-init-sql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4
          envFrom:
            - configMapRef:
                name: pgadmin-secret
          ports:
            - containerPort: 80
          volumeMounts:
            - name: pgadmin-config
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
      volumes:
        - name: pgadmin-config
          configMap:
            name: pgadmin-config
